### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by dheerajbred** [v7lin/fake_okhttp#3]
I don't know if this a mistake but there is nothing in the example

**Comment by droplet-js** [comment]
test/fake_okhttp_test.dart

**Comment by dheerajbred** [comment]
Oh ok. This one worked. Thanks :)

I am actually looking for something that can help me get the HTML response of https://www7.animeultima.eu/ . Unfortunately, fake_okhttp and many other plugins can't do that. Do you have any idea on how to achieve this?

I am closing the issue.
